CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  ward TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE potholes ADD COLUMN IF NOT EXISTS reporter_id UUID REFERENCES users(id);
ALTER TABLE potholes ADD COLUMN IF NOT EXISTS confidence_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE potholes ADD COLUMN IF NOT EXISTS user_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
